services:
  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    hostname: ${RABBITMQ_HOSTNAME}
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_USE_LONGNAME=true
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"   # Application -> RabbitMQ
      - "15672:15672" # Management Dashboard
      - "4369:4369"   # EPMD (Erlang Discovery)
      - "25672:25672" # Internal Cluster Communication (Erlang)
    extra_hosts:
      - "rmq1:${IP_RMQ1}"
      - "rmq2:${IP_RMQ2}"
      - "rmq3:${IP_RMQ3}"
    restart: unless-stopped

volumes:
  rabbitmq_data:
